### ISSUE TITLE
Changed port might cause wrong queue address

### ISSUE THREAD

**Issue by pjungermann** [adamw/elasticmq#87]
When changing just the port `SQSRestServerBuilder`, the `serverAddress` will not get adjusted. Therefore, the resulting queue address is wrong. I used it for tests for an AmazonSQS client and got "queue not found" back. I also tested the address manual, and it was wrong - as it still used the default port.

`NodeAddress` defines the protocol, host, port and context to build a static address string. Still, this string should be in sync with the actual server instance.

This issue is related to #88

**Comment by adamw** [comment]
Ah, I hoped that this would be more clear from the README, but when changing the port you need to change two things current: `SQSRestServerBuilder.withPort(myPort).withServerAddress(NodeAddress(port = myPort))`.

The reason is that the first specifies the port for binding, and the second the port returned in XML responses. These might be different: e.g. in a docker environment, you might bind to an interface/port, but to the outside world, the hostname/port might be different.

Do you have any suggestions on how to improve the API and keep the above functionality?

**Comment by pjungermann** [comment]
I see, I didn't think about the docker use case. I was mainly focused on getting a dynamic port working as described in issue #88. 

I guess my PR is not working for the dockers use case, but was making the rest possible.

Will have a look tomorrow on how I can incorporate that. Maybe you can check it already. Am not much experienced with Scala, but should make it work I guess.

**Comment by pjungermann** [comment]
PS: in my PR I also provided a new method `withDynamicPort`. It might be easy as using an additional dynamic port flag or just a check for port zero or another method asking for synchronized ports, etc.

**Comment by adamw** [comment]
In 0.12.0, when using the Java/Scala API, changing the bind interface/port will also update the node address. Only when a custom node address is specified, bing interface/port won't affect it.

**Comment by pjungermann** [comment]
Sounds great, thanks!
